### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by sjtuzhanglei** [seb-eis/Mocassin#1]
Dear Mocassin developers,

I git cloned the repo and tried to build, but encountered an error:

Could you please help me solve this issue?

Mocassin $ cmake -B ./build -D CMAKE_BUILD_TYPE=Release
CMake Error: The source directory "/global/homes/v/voz5005/Mocassin" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Thanks,

**Comment by seb-eis** [comment]
It seems that you have tried to build the entire repository using cmake. This is not possible. As described in the documentation Mocassin consists of two programs, the windows-only model builder (.net) and the simulator (C), and you can only build the simulator using cmake. To do this by hand as you tried you have to execute the build commands in the src/McSolver directory, as mentioned in the readme on the front page.

**Comment by sjtuzhanglei** [comment]
I see, for Linux system, that's it for installation right? 
So we only need the two binary files to run the whole simulation, right? I.e., Mocassin.Simulator and Mocassin.Utility.

Thanks!

**Comment by seb-eis** [comment]
Yes and no.... You only need Mocassin.Simulator and all affiliated libraries (.so file) the cmake build process creates to run the simulation, the utility binary is a relic that serves little purpose. However, the simulator alone has no value without the model building system, since the latter generates the input for simulations, you cannot create these by hand. The process is basically "Define model > Define set of simulation parameters for model > create simulation input > feed simulation data to the simulator " and the first three steps are provided by the model builder system which can more conveniently be used through the windows GUI. If you want to do model building on a linux machine directly, you need to include the nuget packages in the release zip file into a donet project and write C# code.

I highly recommend you download the release zip, there is a set of HTML documentstion pages included that explain how to install and use Mocassin.

**Comment by sjtuzhanglei** [comment]
During VM set-up process, the VS Build Mocassin.UI.GUI, I found an error:


Mocassin.UI.Installer\Mocassin.UI.Installer.wixproj: The application which this project type is based on was not found. Please try this link for further information: 930c7802-8a8c-48f9-8165-68863bccd9dd

**Comment by sjtuzhanglei** [comment]
PS C:\Users\sjtuz\source\Mocassin\build> Build-Mocassin
Building Mocassin in: C:\Users\sjtuz\source\Mocassin
Updating repository and restoring ... 
Already up to date.
  Determining projects to restore...
  All projects are up-to-date for restore.
Running build scripts with active config JSON
Sourcing helper functions ...
MSBuild is no defined, searching ...
Get-VSSetupInstance: C:\Users\sjtuz\source\Mocassin\build\subscripts\helper-functions.ps1:4:24
Line |
   4 |      $vsSetupInstance = Get-VSSetupInstance
     |                         ~~~~~~~~~~~~~~~~~~~
     | The term 'Get-VSSetupInstance' is not recognized as a name of a cmdlet, function, script file, or executable program.
     | Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Exception: C:\Users\sjtuz\source\Mocassin\build\subscripts\helper-functions.ps1:7:9
Line |
   7 |          throw "Could not locate MSBuild."
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not locate MSBuild.

**Comment by sjtuzhanglei** [comment]
I think I successfully came to the last step, but I checked the build/deploy, there is no tree file, nothing but a zero byte build.log:

 C:\Users\sjtuz\source\Mocassin> Build-Mocassin
Building Mocassin in: C:\Users\sjtuz\source\Mocassin
Updating repository and restoring ...
Already up to date.
  Determining projects to restore...
  All projects are up-to-date for restore.
Running build scripts with active config JSON
Sourcing helper functions ...
MSBuild is no defined, searching ...
MSBuild located at: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
Build version  :  1.1.8310.41365
Build directory:  C:\Users\sjtuz\source\Mocassin\build/deploy/Mocassin-1.1.8310.41365
Build log file :  C:\Users\sjtuz\source\Mocassin\build/deploy/Mocassin-1.1.8310.41365/build.log
Invoking scripts ...
Build process reached end!

**Comment by seb-eis** [comment]
Have you openened the build template JSON file and activated the subscripts that you want to be executed? The template in the repository has all subscripts deactivated, so it only performs pre-build tasks like checking for MSBuild. Based on the log contents you posted I would guess this is your issue. But I do not understand why you are trying to build the Windows part yourself, the Release 1.0.9 contains the current version as an Installer (.msi) for Windows systems. If you complete the VM based build process, you will just get a zip file containig exactly what is contained in the release zip.

**Comment by sjtuzhanglei** [comment]
Here is my template file:

{
    "IsTestMode": false,
    "Source": {
        "ModelBuilderDirectory": "../src/ModelBuilder",
        "ModelBuilderWixProject": "../src/ModelBuilder/Mocassin.UI.Installer/Mocassin.UI.Installer.wixproj",
        "NugetDirectory": "../src/ModelBuilder/nuget",
        "InstallerDirectory": "../src/ModelBuilder/Mocassin.UI.Installer/bin/x64/Release",
        "SolverDirectory": "../src/McSolver",
        "SolverLatestBuildDirectory" : "../src/McSolver/cmake-build-latest",
        "KatexDirectory": "./katex",
        "StylesDirectory": "./styles",
        "DocsDirectory": "../docs",
        "GuidePagesDirectory": "../docs/userguide-md",
        "LicensesDirectory": ""
    },
    "Deploy": {
        "RootDirectory": "$PWD/deploy",
        "RelativeNugetPath": "mocassin-nuget",
        "RelativeGuiPath": "mocassin-win64-gui",
        "RelativWin64SolverPath": "mocsim-win-x86-64",
        "RelativeLinuxDeployPath": "mocsim-linux-x86-64",
        "RelativeDocPath": "doc",
        "RelativeGuidePagesPath" : "doc/guide-pages",
        "PandocCss": "github-pandoc.css",
        "LogFileName": "build.log"
    },
    "Tmp": {
        "Windows": {
            "RelativeSolverBuildPath": ".mocsim-build-tmp"
        },
        "Linux": {
            "SolverBuildDirectory": "$HOME/.mocsim-build-tmp"
        }
    },
    "Compilers": {
        "Windows": {
            "MinGwMake": "C:/msys64/mingw64/bin/mingw32-make.exe",
            "MSBuild": ""
        },
        "Linux": {
            "CCompiler": "gcc"
        }
    },
    "Remote": {
        "CompiledFilesPattern": "*.so Mocassin*",
        "CopyFolderExcludes": [
            ".*",
            "*cmake*",
            "Scripts",
            "UnitTesting",
            "ReadMe",
            "venv"
        ],
        "CopyFileIncludes": [
            "CMakeLists.txt"
        ],
        "LinuxRemotes": [
            {
                "Name": "centos",
                "Host": "voz5005@cori.nersc.gov",
                "PreBuildCommands": [
                    "module unload gcc",
                    "module load gcc/10"
                ]
            }
        ]
    },
    "Scripts": [
        {
            "Path": "./subscripts/build-documentation.ps1",
            "IsActive": true
        },
        {
            "Path": "./subscripts/build-solver-linuxremote.ps1",
            "IsActive": true
        },
        {
            "Path": "./subscripts/build-solver-local.ps1",
            "IsActive": true
        },
        {
            "Path": "./subscripts/build-gui-installer.ps1",
            "IsActive": true
        },
        {
            "Path": "./subscripts/build-nuget-local.ps1",
            "IsActive": true
        }
    ],
    "Meta": {
        "Version" : {
            "Major" : 1,
            "Minor" : 1
        }
    }
}

**Comment by sjtuzhanglei** [comment]
> But I do not understand why you are trying to build the Windows part yourself, the Release 1.0.9 contains the current version as an Installer (.msi) for Windows systems. If you complete the VM based build process, you will just get a zip file containig exactly what is contained in the release zip.

What is the Release 1.0.9 and where to find it? So you mean there is a short-cut to the Mocassin pre-built?

**Comment by sjtuzhanglei** [comment]
I followed step-by-step in the docs/build-vm-setup. Should I follow a different document?

**Comment by seb-eis** [comment]
You can find the latest release here:
[https://github.com/seb-eis/Mocassin/releases/tag/v1.0.9](https://github.com/seb-eis/Mocassin/releases/tag/v1.0.9)

FYI: Your template looks good. The fact that your build.log does not seem to contain any stdout text or any errors from any subscript invocations surprises me a little. If there were issues, I would have expected it to throw some errors and if everything had worked as expected, you should have quite an amount of text informing you about the build process.

It almost seems as if this part of the main build script didn't do anything, which could only be the case if the list of subscripts loaded form the JSON file is empty:

```ps1
Write-Host "Invoking scripts ..."
foreach ($script in $Settings.Scripts) {
    if ($script.IsActive) {
        try {
            Write-Host "Running script : " $script.Path
            & $script.Path -Settings $Settings 3>&1 2>&1 | Write-Log -FilePath $deployLogFile
            Write-Host "Finished script: " $script.Path      
        }
        catch {
            Write-Warning ($script.Path + " has failed with an error: `n`t$_")
        }
    }
}
```

**Comment by sjtuzhanglei** [comment]
Since I already have the release 1.0.9, I installed it on VM Windows 10 using the installer. I should be all set with the installation, right?

The Mocassin GUI in VM seems quite slow and freeze now and then, is it because I should activate windows? The watermark in the GUI tells me to go to settings to activate window.

**Comment by seb-eis** [comment]
Yeah, if the GUI works the installation is done. I have never experienced the GUI to stutter or freeze, even in a VM. Could you check the performance monitor of the task manager in the VM while the UI is running? Maybe you need to allocate a little more resources in the VM settings? I have never tested the UI in an unactivated windows installation, thus I cannot tell you if this can affect performance. Its a simple UI, it should not stutter, even on a low end system.

**Comment by sjtuzhanglei** [comment]
Got it. Thanks! The only thing reminds me is that the number of process core is 1, which in VM it does not allow me to make my selection to 2 or more.

**Comment by seb-eis** [comment]
That is probably it. One core for a win 10 Installation is not enough. There should be a setting in your BIOS which enables enhanced virtualization support by the CPU. It may be that Virtual Box requires this to be enabled to allow multiple cores for the VM.

**Comment by seb-eis** [comment]
I will close this issue since it seems to be resolved.
