### ISSUE TITLE
cannot delete entries in the model building

### ISSUE THREAD

**Issue by sjtuzhanglei** [seb-eis/Mocassin#2]
Dear Mocassin developers,

If I entered a wrong particle or particle set entry, I cannot delete it. What should I do to correct it?

Thanks,

**Comment by seb-eis** [comment]
Data grid entries are removed by selecting the entry in the grid and pressing the 'DELETE' key.

**Comment by seb-eis** [comment]
I close this issue since it seems to be resolved.
